### ISSUE TITLE
Server Crash | Eliminating player on fog map

### ISSUE THREAD

**Issue by Theodorelankford** [spqr-game/spqr-issues#89]
Could not capture it but I just had a server crash when I eliminated someone in fog map for ants
https://spqr.app/game/play?id=956
Sept 27th 2024 7:20 AM PST Roughly
The server crashed after confirming the attack, When it came back it awarded me the cards and was forcing me to turn in cards
And I can see path4729 for some reason which shows an eliminated player
![Image](https://github.com/user-attachments/assets/36b682f3-0290-479b-8162-136ff9801143)

**Comment by chad3814** [comment]
here's the log around that time, seems unrelated:
```
2024-09-27T13:20:07.359850397Z call failed, would've sent message to user (62) of "Memento Mori. It is your turn in <https://spqr.app/game/play?id=1130|organic highlight | Vikingr by Yuma (Vikingr by Yuma)>" Error: An API error occurred: channel_not_found
2024-09-27T13:20:07.359922648Z     at platformErrorFromResult (/app/node_modules/@slack/web-api/dist/errors.js:62:33)
2024-09-27T13:20:07.359932868Z     at WebClient.apiCall (/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)
2024-09-27T13:20:07.359940019Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-27T13:20:07.359946369Z     at async C (/app/.next/server/chunks/5663.js:1:103676)
2024-09-27T13:20:07.359952559Z     at async c.onTurn (/app/.next/server/chunks/5663.js:1:89122) {
2024-09-27T13:20:07.359959039Z   code: 'slack_webapi_platform_error',
2024-09-27T13:20:07.359965449Z   data: {
2024-09-27T13:20:07.359971659Z     ok: false,
2024-09-27T13:20:07.359976599Z     error: 'channel_not_found',
2024-09-27T13:20:07.359981689Z     response_metadata: { scopes: [Array], acceptedScopes: [Array] }
2024-09-27T13:20:07.359986879Z   }
2024-09-27T13:20:07.359991680Z }
```

**Comment by chad3814** [comment]
okay according to the DB, path4729, countryId 1, is owned by Buttered Popcorn, not The Blob.
Here are the last actions:

| id| Time | Action |
|--------|--------|--------|
| 1317179 | 14:22:21.682 | Rux captures countryId 207 |
| 1317180 | 14:22:21.682 | Rux eliminates The Blob, getting 2 units |
| 1317181 | 14:22:21.682 | Rux gets five cards |
| 1317182 | 14:22:21.682 | Rux is in unit placement |
| 1317184 | 14:22:28.075 | Rux transfers 57 unit to countryId 207 from 208 |
| 1317188 | 14:24:47.001 | Rux turns in 3 cards for 4 units |
| 1317189 | 14:25:14.580 | Rux places 6 units in countryId 1 |
| 1317190 | 14:25:14.580 | Rux places 0 units in countryId 207 |
| 1317191 | 14:25:19.415 | Rux places 0 units in countryId 207 (again?) |
| 1317192 | 14:25:19.415 | Rux removes 6 units from countryId 1 |
| 1317193 | 14:25:25.580 | Rux places 6 units in countryId 85 |
| 1317194 | 14:25:33.593 | Rux removes 6 units from countryId 85 |
| 1317238 | 14:29:40.521 | Rux places 0 units in countryId 1 |
| 1317239 | 14:29:40.521 | Rux places 6 units in countryId 207 |
| 1317243 | 14:30:09.626 | Rux chats |

**Comment by Theodorelankford** [comment]
Is the fact that The Blob nudged people out of games count for anything in this issue?

**Comment by chad3814** [comment]
here's the server log during the 14:21 time:
```
2024-09-27T14:21:18.840688719Z no slackid for user, would've sent message to user (129) of "Memento Mori. It is your turn in <https://spqr.app/game/play?id=1101|inexperienced advance | New Players | U… (USA)>"
2024-09-27T14:21:22.342478698Z call failed, would've sent message to user (62) of "Et tu, Strifer? You've been eliminated from <https://spqr.app/game/play?id=1150|jumpy construction (FFA) (Arkeanos)>" Error: An API error occurred: channel_not_found
2024-09-27T14:21:22.342556109Z     at platformErrorFromResult (/app/node_modules/@slack/web-api/dist/errors.js:62:33)
2024-09-27T14:21:22.342566069Z     at WebClient.apiCall (/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)
2024-09-27T14:21:22.342573579Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-27T14:21:22.342581189Z     at async C (/app/.next/server/chunks/5663.js:1:103676)
2024-09-27T14:21:22.342588270Z     at async c.onDeath (/app/.next/server/chunks/5663.js:1:88257) {
2024-09-27T14:21:22.342631350Z   code: 'slack_webapi_platform_error',
2024-09-27T14:21:22.342638831Z   data: {
2024-09-27T14:21:22.342645691Z     ok: false,
2024-09-27T14:21:22.342651711Z     error: 'channel_not_found',
2024-09-27T14:21:22.342657541Z     response_metadata: { scopes: [Array], acceptedScopes: [Array] }
2024-09-27T14:21:22.342663721Z   }
2024-09-27T14:21:22.342669971Z }
```
Only slack errors

**Comment by chad3814** [comment]
okay, here are the players:
| seatNumber | name | userId | color | isAlive |
|---------|----------|-------|---|-----|
| 0 | kquetano | 63 | 5-Pink | Yes |
| 1 | Nathann64 | 82 | 10-Green | Yes |
| 2 | Ruxzbin | 51 | 11-Purple | Yes |
| 3 | The Blob | 61 | 14-Orange | No |
| 4 | A-Mo | 54 | 1-Lime | Yes |
| 5 | Tangoteeth | 128 | 8-Maroon | No |
| 6 | buttered popcorn | 62 | 3-Yellow | No |
| 7 | Strifer | 119 | 0-Red | No |

and here are some of the the nudge and surrender actions:
| id | ts | actionType | data |
|-------|-------|-------|-----------|
| 1023897 | 2024-07-23 21:42:14.211 | Nudge | The Blob nudges Ruxzbin |
| 1025511 | 2024-07-24 17:35:07.785 | Surrender | buttered popcorn surrenders |
| 1025735 | 2024-07-24 18:35:50.346 | Nudge | The Blob nudges Strifer |
| 1195304 | 2024-09-01 16:45:19.358 | Nudge | The Blob nudges Tangoteeth |
| 1198564 | 2024-09-02 20:17:23.237 | Surrender | Strifer surrenders |
| 1239957 | 2024-09-06 18:12:59.689 | Surrender | The Blob surrenders |
| 1241833 | 2024-09-07 02:27:27.792 | Nudge | The Blob nudges Tangoteeth |
| 1314834 | 2024-09-27 03:04:33.671 | Nudge | The Blob nudges Tangoteeth |
|1314835 | 2024-09-27 03:04:33.671 | Surrender | Tangoteeth surrenders (automated from the nudge) |

**Comment by chad3814** [comment]
It's possible that there's an error when you eliminate a dead player (because they surrendered)

**Comment by chad3814** [comment]
okay, the fact that Rux can see Buttered Popcorn's countryId 1 is valid, they are on the same team, and that's BP's only country.
